FROM node:18-alpine AS builder

WORKDIR /server

COPY package*.json /app/

RUN npm ci

COPY . .

RUN npm run build

FROM node:18-alpine as production

COPY --from=builder ./dist .

ENV NODE_ENV=production

EXPOSE 3000

CMD node ./dist/api.js