version: "3.1"

services:
  db:
    image: postgres:16-alpine
    container_name: PostgresDB
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
